name:                tungsten
version:             0.1.0.0
github:              "nobrakal/tungsten"
license:             BSD3
author:              "Alexandre Moine"
maintainer:          "alexandre@moine.me"
copyright:           "2019 Alexandre Moine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Bring fusion to everyone
category:            Recursion, Optimization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobrakal/tungsten#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  tungsten-test:
    main:                Main.hs
    source-dirs:         test
    dependencies:
    - tungsten
    - inspection-testing >= 0.4 && < 0.5